sudo: required

language: node_js

node_js:
  - 4
  - 6
  - 8
  - 10

env:
  matrix:
    - MONGODB=3.4
    - MONGODB=3.6

services:
  - docker

before_script:
  - docker run -d -p 27017:27017 mongo:$MONGODB

script:
  - npm run lint
  - travis_retry MONGODB_URL=mongodb://localhost/connect-mongo-test npm test

after_success:
  - npm install coveralls -g && npm run cover | coveralls
